name: workflow-for-Java-app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache maven dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mvn -B install -DskipTests

      - name: Run Checkstyle
        run: mvn -B checkstyle:check

      - name: Run Tests
        run: mvn -B verify
      
      - name: Build JAR
        run: mvn -B package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: flappy-bird-jar
          path: target/*.jar